<#
.SYNOPSIS
    Configure and publish the MoodJournal frontend after a SAM deployment.

.DESCRIPTION
    Run this after `sam deploy`. It reads the CloudFormation stack outputs,
    writes the API Gateway URL into frontend/js/config.js, uploads the frontend
    to the S3 bucket, and invalidates the CloudFront cache so visitors get the
    new files immediately.

    frontend/js/config.js is the only file that carries the API address, so no
    HTML or JS needs editing by hand. The local copy is restored afterwards
    unless -KeepLocalConfig is passed, so local development keeps working.

.PARAMETER StackName
    CloudFormation stack name used with `sam deploy`. Default: moodjournal-stack

.PARAMETER Region
    AWS region the stack was deployed to. Default: the configured CLI region.

.PARAMETER KeepLocalConfig
    Leave config.js pointing at the deployed API instead of restoring the
    local default.

.EXAMPLE
    .\scripts\deploy_frontend.ps1 -StackName moodjournal-stack -Region us-east-1
#>

[CmdletBinding()]
param(
    [string]$StackName = "moodjournal-stack",
    [string]$Region,
    [switch]$KeepLocalConfig
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $projectRoot "frontend\js\config.js"
$frontendDir = Join-Path $projectRoot "frontend"

if (-not $Region) {
    $Region = (aws configure get region)
    if (-not $Region) { throw "No region given and none configured. Pass -Region." }
}

Write-Host "Stack : $StackName" -ForegroundColor Cyan
Write-Host "Region: $Region" -ForegroundColor Cyan

# --- 1. Read the stack outputs -------------------------------------------
Write-Host "`n[1/4] Reading stack outputs..." -ForegroundColor Cyan

$outputsJson = aws cloudformation describe-stacks `
    --stack-name $StackName --region $Region `
    --query "Stacks[0].Outputs" --output json
if ($LASTEXITCODE -ne 0) { throw "Could not read stack '$StackName'. Has it been deployed?" }

$outputs = @{}
foreach ($o in ($outputsJson | ConvertFrom-Json)) { $outputs[$o.OutputKey] = $o.OutputValue }

$apiUrl = $outputs["ApiEndpoint"]
$bucket = $outputs["FrontendBucketName"]
$cloudFrontUrl = $outputs["CloudFrontUrl"]

foreach ($pair in @(@("ApiEndpoint", $apiUrl), @("FrontendBucketName", $bucket))) {
    if (-not $pair[1]) { throw "Stack output '$($pair[0])' is missing." }
}

Write-Host "  API        : $apiUrl"
Write-Host "  Bucket     : $bucket"
Write-Host "  CloudFront : $cloudFrontUrl"

# CloudFront's distribution id is not a stack output, so find it by matching
# the domain name of the distribution the stack created.
$cfDomain = ($cloudFrontUrl -replace "^https?://", "").TrimEnd("/")
$distributionId = aws cloudfront list-distributions `
    --query "DistributionList.Items[?DomainName=='$cfDomain'].Id | [0]" `
    --output text
if ($distributionId -eq "None") { $distributionId = $null }

# --- 2. Write the deployed config ----------------------------------------
Write-Host "`n[2/4] Writing frontend/js/config.js..." -ForegroundColor Cyan

$originalConfig = Get-Content $configPath -Raw

$deployedConfig = @"
/**
 * Runtime configuration for the MoodJournal frontend.
 *
 * Generated by scripts/deploy_frontend.ps1 from the outputs of the
 * CloudFormation stack "$StackName". Do not edit by hand.
 */
window.MOODJOURNAL_CONFIG = {
  API_BASE_URL: "$($apiUrl.TrimEnd('/'))",
};
"@

# WriteAllText, not Set-Content: Windows PowerShell's -Encoding utf8 always
# prepends a byte order mark, and a BOM at the top of a .js file is asking for
# an obscure parsing bug somewhere down the line.
[System.IO.File]::WriteAllText($configPath, $deployedConfig)
Write-Host "  API_BASE_URL = $($apiUrl.TrimEnd('/'))"

try {
    # --- 3. Upload to S3 --------------------------------------------------
    Write-Host "`n[3/4] Uploading to s3://$bucket ..." -ForegroundColor Cyan

    # HTML and the config get a short cache life so a redeploy is picked up even
    # before the invalidation lands; static assets can be cached hard.
    aws s3 sync $frontendDir "s3://$bucket" --region $Region --delete `
        --exclude "*.html" --exclude "js/config.js" `
        --cache-control "public,max-age=86400"
    if ($LASTEXITCODE -ne 0) { throw "s3 sync of static assets failed." }

    aws s3 sync $frontendDir "s3://$bucket" --region $Region `
        --exclude "*" --include "*.html" --include "js/config.js" `
        --cache-control "no-cache"
    if ($LASTEXITCODE -ne 0) { throw "s3 sync of HTML/config failed." }

    # --- 4. Invalidate CloudFront ----------------------------------------
    Write-Host "`n[4/4] Invalidating CloudFront..." -ForegroundColor Cyan
    if ($distributionId) {
        aws cloudfront create-invalidation `
            --distribution-id $distributionId --paths "/*" `
            --query "Invalidation.Id" --output text | Out-Null
        Write-Host "  Invalidated distribution $distributionId"
    }
    else {
        Write-Host "  Could not resolve the distribution id; invalidate manually." -ForegroundColor Yellow
    }
}
finally {
    if (-not $KeepLocalConfig) {
        [System.IO.File]::WriteAllText($configPath, $originalConfig)
        Write-Host "`nRestored the local config.js (use -KeepLocalConfig to keep the deployed one)."
    }
}

Write-Host "`nDone. Open: $cloudFrontUrl" -ForegroundColor Green
Write-Host "Health check: $($apiUrl.TrimEnd('/'))/health" -ForegroundColor Green
